# This workflow will install Python dependencies, run tests and lint with a
# single version of Python. For more information see:
# https://help.github.com/actions/language-and-framework-guides\
# /using-python-with-github-actions

name: Test migration scripts

on:
  push:
    branches: ["15.0*"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB: "viin_upgrade"
      DB_HOST: "localhost"
      DB_PASSWORD: "viindoo"
      DB_PORT: 5432
      DB_USERNAME: "viindoo"
      DOWNLOADS: https://github.com/Viindoo/OpenUpgrade/releases/download/databases
      ODOO: "./odoo/odoo-bin"
      PGHOST: "localhost"
      PGPASSWORD: "viindoo"
      PGUSER: "viindoo"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Configure Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "12"
          postgresql user: ${DB_USERNAME}
          postgresql password: ${DB_PASSWORD}
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: "10s"
      - name: DB Creation
        run: createdb $DB
      - name: DB Restore
        run: |
          psql -d $DB -c "DROP SCHEMA IF EXISTS PUBLIC;"
          wget -q -O- $DOWNLOADS/14.0.psql | pg_restore -d $DB --no-owner
          # TODO: create test data in Odoo 13.0 which does not support yml
          # anymore
          # Roundtrip to previous release to update the test database with
          # additional test data
          # - git fetch --depth 2 origin 13.0
          # - git reset --hard `git ls-remote \
          #       | grep refs/heads/13.0 \
          #       | awk '{print $1}'`
          # - pip install -q -r requirements.txt
          # Line below may fail quite often due to Travis bug:
          # - git reset -q --hard $TRAVIS_COMMIT
          # Install Python requirements of target release
      - name: Check out Viindoo/Odoo
        uses: actions/checkout@v3
        with:
          repository: Viindoo/odoo
          ref: "15.0"
          fetch-depth: 1
          path: odoo
      - name: Check out Viindoo/OpenUpgrade
        uses: actions/checkout@v3
        with:
          path: openupgrade
      - name: Configuration
        run: |
          sudo apt update
          sudo apt install \
              expect \
              expect-dev \
              libevent-dev \
              libldap2-dev \
              libsasl2-dev \
              libxml2-dev \
              libxslt1-dev \
              nodejs \
              python3-lxml \
              python3-passlib \
              python3-psycopg2 \
              python3-serial \
              python3-simplejson \
              python3-werkzeug \
              python3-yaml \
              unixodbc-dev
      - name: Requirements Installation
        run: |
          sudo npm install -g less less-plugin-clean-css
          pip install -q -r odoo/requirements.txt
          pip install --ignore-installed \
              git+https://github.com/OCA/openupgradelib.git@master
          # select modules and perform the upgrade
      - name: OpenUpgrade test
        run: |
          MODULES_TO_UPGRADE=$(\
              sed -n '/^+========/,$p' \
              openupgrade/docsource/modules140-150.rst \
              | grep -v "Done\|Partial\|Nothing" \
              | grep -v "theme_" \
              | sed -rn 's/((^\| *)|^\|)([0-9a-z_]*) *\|.*$/\3/g p' \
              | sed '/^\s*$/d' \
              | paste -d, -s)
          MODULES_TO_TEST=base,$(\
              sed -n '/^+========/,$p' \
              openupgrade/docsource/modules140-150.rst \
              | grep "Done\|Partial\|Nothing" \
              | grep -v "theme_" \
              | sed -rn 's/((^\| *)|^\|)([0-9a-z_]*) *\|.*$/\3/g p' \
              | sed '/^\s*$/d' \
              | paste -d, -s)
          psql $DB -c "update ir_module_module set state='uninstalled' \
              where name not in ('$(echo $MODULES_TO_UPGRADE | sed -e "s/,/','/g")')"
          ADDONS_PATHS="\
              $GITHUB_WORKSPACE/odoo/addons \
              $GITHUB_WORKSPACE/odoo/odoo/addons \
              $GITHUB_WORKSPACE/openupgrade"
          echo Testing modules $MODULES_TO_TEST
          # Silence redundant logs from unlinking records (1 line is enough)
          # to prevent log overflow
          OPENUPGRADE_TESTS=1 $ODOO \
              --addons-path=`echo $ADDONS_PATHS | awk -v OFS="," '$1=$1'` \
              --database=$DB \
              --db_host=$DB_HOST \
              --db_password=$DB_PASSWORD \
              --db_port=$DB_PORT \
              --db_user=$DB_USERNAME \
              --load=base,web,openupgrade_framework \
              --log-handler odoo.models.unlink:WARNING \
              --stop-after-init \
              --update=$MODULES_TO_TEST
